### ISSUE TITLE
Ошибка в схеме

### ISSUE THREAD

**Issue by VinokurovSE** [emil817/METEOSTATION#1]
Здравствуйте!
Заметил в [схеме](https://github.com/emil817/METEOSTATION/blob/main/Scheme.jpg) ошибку - к RTC не подведена линия тактирования.

Но это повод написать. Причина в том, что других способов связи я с вами я не нашёл. Скажите, как можно с вами связаться? В приоритете telegram и email.

**Comment by emil817** [comment]
Здравствуйте, спасибо за замечание, исправил.
